In [1]:
from cb_tf_idf import timestamp_diffs

In [2]:
timestamp_diffs( 'Risk Factors', ['jnj', 'msft'])

HBox(children=(IntProgress(value=0, max=2), HTML(value='')))

                                distance  word_count
ticker timestamp
jnj    2010-03-01 16:50:02.000       NaN          25
       2011-02-25 05:30:00.000  0.026355          24
       2012-02-23 17:11:21.000  0.000000          24
       2013-02-22 05:30:00.000  0.041821          24
       2014-02-21 14:29:51.000  0.000000          24
       2015-02-24 05:30:00.000  0.569617          46
       2016-02-24 16:58:53.000  0.020174          44
       2017-02-27 16:52:48.000  0.607054        1973
       2018-02-21 17:14:43.253  0.010157        2041
       2019-02-20 17:02:46.800  0.021016        2190
msft   2009-10-23 08:34:21.000       NaN        2217
       2010-01-28 16:11:45.000  0.004789        2253
       2010-04-22 16:18:52.000  0.002125        2310
       2010-07-30 11:30:38.000  0.022459        2436
       2010-10-28 16:36:15.000  0.003732        2502
       2011-01-27 16:00:33.000  0.000093        2498
       2011-04-28 16:09:30.000  0.001325        2513
       2011-07-28 14:59:09.000  0.016410        2722
       2011-10-20 16:08:23.000  0.002151        2744
       2012-04-19 16:06:08.000  0.003499        2833
       2012-07-26 16:12:48.000  0.029596        3348
       2012-10-18 16:04:23.000  0.005206        3206
       2013-01-24 16:10:59.000  0.001479        3190
       2013-04-18 16:07:37.000  0.003852        3206
       2013-07-30 16:14:49.000  0.005094        3275
       2013-10-24 16:08:05.000  0.009737        3460
       2014-01-23 16:08:44.000  0.004587        3502
       2014-04-24 16:06:04.000  0.003797        3430
       2014-07-31 17:16:52.000  0.026855        3484
       2014-10-23 16:16:17.000  0.003486        3545
       2015-01-26 16:13:49.000  0.002302        3603
       2015-04-23 16:09:01.000  0.003494        3651
       2015-07-31 15:07:52.000  0.010446        3556
       2015-10-22 16:10:04.000  0.002525        3553
       2016-01-28 16:11:24.000  0.006118        3702
       2016-04-21 16:10:33.000  0.000604        3739
       2016-07-28 16:12:18.000  0.005968        3816
       2016-10-20 16:10:25.000  0.005080        3824
       2017-01-26 16:13:28.000  0.006876        3949
       2017-04-27 16:24:50.357  0.000213        3953
       2017-08-02 16:32:07.413  0.004270        4030
       2017-10-26 16:25:41.293  0.005573        4190
       2018-01-31 16:38:14.813  0.001746        4311
       2018-04-26 16:28:20.030  0.002007        4371
       2018-08-03 12:39:36.660  0.016915        4860
       2018-10-24 16:34:56.430  0.002254        4854
       2019-01-30 16:52:42.320  0.000428        4868